// New file: lib/model/OrderModel.dart

import 'package:tryon/model/CartItem.dart';

class OrderModel {
  final String? id; // Auto-generated by Firebase
  final String userId;
  final String userName;
  final String userEmail;
  final String shippingAddress;
  final List<CartItem> products;
  final double totalAmount;
  final DateTime orderDate;
  final String status; // e.g., 'pending', 'shipped', 'delivered'

  OrderModel({
    this.id,
    required this.userId,
    required this.userName,
    required this.userEmail,
    required this.shippingAddress,
    required this.products,
    required this.totalAmount,
    required this.orderDate,
    required this.status,
  });

  // toMap for Firebase serialization
  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'userName': userName,
      'userEmail': userEmail,
      'shippingAddress': shippingAddress,
      'products': products.map((item) => item.toMap()).toList(),
      'totalAmount': totalAmount,
      'orderDate': orderDate.toIso8601String(),
      'status': status,
    };
  }

  // fromMap for deserialization
  factory OrderModel.fromMap(String id, Map<String, dynamic> map) {
    return OrderModel(
      id: id,
      userId: map['userId'] ?? '',
      userName: map['userName'] ?? '',
      userEmail: map['userEmail'] ?? '',
      shippingAddress: map['shippingAddress'] ?? '',
      products: (map['products'] as List<dynamic>? ?? [])
          .map((itemMap) => CartItem.fromMap(itemMap as Map<String, dynamic>))
          .toList(),
      totalAmount: map['totalAmount']?.toDouble() ?? 0.0,
      orderDate: DateTime.tryParse(map['orderDate'] ?? '') ?? DateTime.now(),
      status: map['status'] ?? 'pending',
    );
  }
}
