// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzwiZbsdxd4C8ouHlh1fzuaTK7F_P_Ew',
    appId: '1:101100602179:web:82d00cc6bc093e84dca5f6',
    messagingSenderId: '101100602179',
    projectId: 'spot-holder',
    authDomain: 'spot-holder.firebaseapp.com',
    storageBucket: 'spot-holder.appspot.com',
    measurementId: 'G-YZ5N1RN41P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE3TYpvaGcsniFZKx7SVgHFyrfMA22G0w',
    appId: '1:101100602179:android:34e06f02e235a7c7dca5f6',
    messagingSenderId: '101100602179',
    projectId: 'spot-holder',
    storageBucket: 'spot-holder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5FgXnmNPOVo69vHPb94r3IMkf-fVI7jo',
    appId: '1:101100602179:ios:2b3721ba6b8320d1dca5f6',
    messagingSenderId: '101100602179',
    projectId: 'spot-holder',
    storageBucket: 'spot-holder.appspot.com',
    iosBundleId: 'com.example.tryon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5FgXnmNPOVo69vHPb94r3IMkf-fVI7jo',
    appId: '1:101100602179:ios:2b3721ba6b8320d1dca5f6',
    messagingSenderId: '101100602179',
    projectId: 'spot-holder',
    storageBucket: 'spot-holder.appspot.com',
    iosBundleId: 'com.example.tryon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpzwiZbsdxd4C8ouHlh1fzuaTK7F_P_Ew',
    appId: '1:101100602179:web:efe9fae3edd53b6adca5f6',
    messagingSenderId: '101100602179',
    projectId: 'spot-holder',
    authDomain: 'spot-holder.firebaseapp.com',
    storageBucket: 'spot-holder.appspot.com',
    measurementId: 'G-D6KL5FRCQH',
  );
}
